spring:
  application:
    name: Associate-Service
server:
  port: 9111
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
